# Generated by Django 3.2.15 on 2022-11-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ePrescribe', '0002_alter_patient_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admin',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suburb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.suburb'),
        ),
    ]
